In [21]:
import requests
import setup as mongler
import pandas as pd
import time as time
from pymongo import MongoClient

## Configure mongo
mongo_client = MongoClient(mongler.MONGO_ADDRESS,mongler.MONGO_PORT)
reportsDB = mongo_client.BYUbridge.reports

## Make requests to bridge for list of reports
headers = {"Authorization":"Token %s" % mongler.TOKEN}

## returns all of the reports on the bridge that contain an exact match to a keyword
def GetReportList(keyword):
    reports = []
    pageNum = 1
    while True:
        payload = {'page':pageNum, 'perPage':'100'}
        r = requests.get('https://byu-csm.symplicity.com/api/public/v1/reports', params = payload, headers=headers)
        models = r.json()['models']
        if len(models) == 0:
            break
        else:
            reports.append(models)
            pageNum += 1

    ### Find reports with the name ADRIEL in the Label
    keywordReports = []
    for page in reports:
        for report in page:
            if keyword in report['label']:
                keywordReports.append(report)

    ## This will print all of the reports
    return keywordReports

## Run the desired report
def RunReport(reportID, headers, payload):
    request = requests.put('https://byu-csm.symplicity.com/api/public/v1/reports/%s/run' %reportID, headers=headers)
    ## This while loop waits until the most recent report to be completed
    while True:
        time.sleep(6)
        ## this payload will request only the most recent run
        tmp_payload = {'page':'1', 'perPage':'1'}
        r = requests.get('https://byu-csm.symplicity.com/api/public/v1/reports/%s/runs' %reportID, params = tmp_payload, headers=headers)
        tmp = r.json()
        if tmp['models'][0]['label'] == 'complete':
            break
    ## Once the report is run and completed, get the report run data
    request = requests.get('https://byu-csm.symplicity.com/api/public/v1/reports/%s/data' %reportID, headers=headers, params=payload)
    df = pd.read_json(request.json())

    ## Use row 1 as the header for the column names and then drop the row
    df.columns = df.iloc[0]
    return df.reindex(df.index.drop(0))

## This Main function will run all the desired reports given a certain keyword
def main():
    ## Get the list of Reports
    adrielReports = GetReportList('ADRIEL')
    print(adrielReports)

    ## Name all of the reports based on label
    for i, report in enumerate(adrielReports):
        if 'Full Student List' in report['label']:
            fullStudent = report
        elif 'Archived Events' in report['label']:
            archivedAttendees = report
        elif 'Non-archived' in report['label']:
            nonArchivedEvents = report
        else:
            print("Named %n reports" %(i +1))
            break

    ## Run reports
    payload = {'format':'csv'}
    studentReport = RunReport(fullStudent['id'], headers, payload)
    attendeeReport = RunReport(archivedAttendees['id'], headers, payload)
    attendeeReport2 = RunReport(nonArchivedEvents['id'], headers, payload)

    ## Append the attendee reports and merge
    attendeeReport = attendeeReport.append(attendeeReport2)
    attendeeReport = attendeeReport.merge(studentReport, left_on='Kiosk Swipe Log: student', right_on='Name')
    attendeeReport.to_csv(path_of_buf = '~/MAIN/BCC/Club\ data/attendeeReport.csv')

In [5]:
adrielReports = GetReportList('ADRIEL')

In [17]:
for i, report in enumerate(adrielReports):
    if 'Full Student List' in report['label']:
            fullStudent = report
    elif 'Archived Events' in report['label']:
            archivedAttendees = report
    elif 'Non-archived' in report['label']:
            nonArchivedEvents = report
    else:
        print("Named %n reports, ERROR" %(i +1))
        break

In [18]:
payload = {'format':'csv'}

In [22]:
studentReport = RunReport(fullStudent['id'], headers, payload)

ValueError: Trailing data

In [20]:
studentReport

0                              Name
1                             Email
2                        First Name
3                         Last Name
4                   Graduation Date
5                        Student ID
6      Christopher Matthew Melville
7             cmelville23@gmail.com
8               Christopher Matthew
9                          Melville
10                     Dec 01, 2017
11                        398678447
12           Jacob Leonard Marshall
13       newzealandcougar@gmail.com
14                            Jacob
15                         Marshall
16                     Dec 01, 2017
17                        107664349
18               Ivan Edward Bowles
19            ivanebowles@gmail.com
20                      Ivan Edward
21                           Bowles
22                     Dec 01, 2017
23                        368869312
24              Jenny Logan Lapides
25               jlapides@ymail.com
26                      Jenny Logan
27                          Lapides
28                     Dec 01, 2017
29                        152918578
30                        Alex W La
...                             ...
45552           Brock Strong Rawson
45553           brawsters@gmail.com
45554                  Brock Strong
45555                        Rawson
45556                  Jun 01, 2022
45557                     537905945
45558             Shayna Tak-Yin Oh
45559        oh.shayna.ty@gmail.com
45560                Shayna Tak-Yin
45561                            Oh
45562                  Jun 01, 2022
45563                     621955880
45564             Alec Bench Cutler
45565            5cutlers@gmail.com
45566                    Alec Bench
45567                        Cutler
45568                  Jun 01, 2022
45569                     266631520
45570       Nathan William Levander
45571        n.w.levander@gmail.com
45572                Nathan William
45573                      Levander
45574                  Aug 01, 2022
45575                     616742430
45576             Lori Lee McMillan
45577       mcmillan91172@gmail.com
45578                          Lori
45579                      McMillan
45580                  Aug 01, 2022
45581                      lmcmill2

[45581 rows x 1 columns]